version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - milvus
    networks:
      - backend
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure

  milvus:
    image: milvusdb/milvus:v2.2.5
    ports:
      - "19530:19530"
    volumes:
      - ./data/milvus:/var/lib/milvus
    networks:
      - backend

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - backend

networks:
  backend:
    driver: bridge
